# Generated by Django 4.2.7 on 2025-10-08 18:19

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Foods', 'Foods'), ('Snacks', 'Snacks'), ('Combo Meals', 'Combo Meals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=sales.models.get_eat_now),
        ),
    ]
